USE [BDUsuario]
GO
CREATE LOGIN [RN] WITH PASSWORD=N'RN', DEFAULT_DATABASE=[BDUsuario], CHECK_EXPIRATION=OFF,
CHECK_POLICY=OFF
GO

USE [BDUsuario]
GO
CREATE USER [RN] FOR LOGIN [RN]
GO
USE [BDUsuario]
GO
ALTER ROLE [db_owner] ADD MEMBER [RN]
GO